[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"